### ISSUE TITLE
Logged-out visitors seem to be getting an old version of an article

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#769] opened 2015-12-23 03:05 UTC
Possibly a caching mechanism got stuck somewhere? If I look at [Varsity Sweet Shop](https://localwiki.org/sf/Varsity_Sweet_Shop) while logged out, I seem to see an older version of the article:

![screen shot 2015-12-22 at 7 02 31 pm](https://cloud.githubusercontent.com/assets/391313/11970377/bb9e107c-a8de-11e5-9fce-5fde46e8a41a.png)

This is what it looks like when logged in, which is the current version (with a photo on top):

![screen shot 2015-12-22 at 7 02 56 pm](https://cloud.githubusercontent.com/assets/391313/11970376/bb9d1f00-a8de-11e5-9797-9b96015ae034.png)

**Comment by philipn** [comment] 2015-12-23 04:14
I see this as well. Are you seeing this / can reproduce elsewhere?

**Comment by brittag** [comment] 2015-12-23 04:29
Checking back through recent edits, very recent edits aren't showing this, but some of the ones older than "last modified 1 day, 21 hours ago" seem to be showing it - for example https://localwiki.org/arlington-heights/Abcor_Home_Health_Chicago and https://localwiki.org/walnut-creek/CVS_Pharmacy .

**Comment by brittag** [comment] 2015-12-23 04:31
https://localwiki.org/ann-arbor/Chris_Easthope also shows it (two days ago). It's not happening to all the articles in these time ranges, just some of them.

**Comment by philipn** [comment] 2015-12-23 23:06
Looks like our `celery` service wasn't properly restarted after the latest deploy.  Should be fixed now!

**Closed as completed by philipn** 2015-12-23 23:06 UTC

**Comment by brittag** [comment] 2015-12-23 23:15
Yay, thank you for fixing this!

**Comment by vielmetti** [comment] 2016-01-11 14:29
Yay!
